### ISSUE TITLE
Add support for Terminator terminal emulator

### ISSUE THREAD

**Issue by mhulscher** [Ikuyadeu/Lucario-vscode#3]
I am using lucario in vscode and it is great. It would be great to have the same colour scheme in my terminal of preference, Terminator.

https://terminator-gtk3.readthedocs.io/en/latest/

**Comment by Ikuyadeu** [comment]
@mhulscher Thank you for using this theme, I will try it to support.
If you want to use the theme in the terminal without vscode, it is supported on https://github.com/raphamorim/lucario

**Comment by mhulscher** [comment]
Thank you. Looks like I opened this issue in the wrong project. Would you like me to close this issue and open a new one in the repo you mentioned?

**Comment by Ikuyadeu** [comment]
I just close this issue, and I recommend you to read the https://github.com/raphamorim/lucario#terminalapp
If you still have a problem, please open on the original repository.
